package gui;

import client.BankingDAO;
import java.awt.Component;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 * Screen with information on selected account
 * 
 * @author Brandon Lawson
 * 
 */

/*
 * Project: CryptographyBankingApplication
 * Course: CMSC 495
 * Date: 02/18/2016
 * 02/21/2016 - Updated by Grant Sweeney
 * 02/28/2016 - Added functionality to buttons - Brandon Lawson
 */

public class AccountInfo extends javax.swing.JFrame {
    
    BankingDAO bankingDAO = new BankingDAO();

    /**
     * Creates new form AccountInfo
     */
    public AccountInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerLabel = new javax.swing.JLabel();
        accountDetailsPanel = new javax.swing.JPanel();
        accountBalanceLabel1 = new javax.swing.JLabel();
        accountTypeLabel1 = new javax.swing.JLabel();
        accountTypeTextField = new javax.swing.JTextField();
        accountNumberTextField1 = new javax.swing.JTextField();
        transactionButton = new javax.swing.JButton();
        accountNumberLabel1 = new javax.swing.JLabel();
        accountBalanceTextField1 = new javax.swing.JTextField();
        depositWithdrawalPanel = new javax.swing.JPanel();
        amountTextField1 = new javax.swing.JTextField();
        depositButton = new javax.swing.JButton();
        withdrawalButton = new javax.swing.JButton();
        amountLabel2 = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();
        payMortgageButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        amountTextField2 = new javax.swing.JTextField();
        accountTextField = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        accountNumberLabel = new javax.swing.JLabel();
        backToCustomerButton = new javax.swing.JButton();
        deleteAccountButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UMUC Bank - Account Info");

        bannerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/UMUC.logo.jpg"))); // NOI18N

        accountDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13))); // NOI18N

        accountBalanceLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        accountBalanceLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountBalanceLabel1.setText("Account Balance");

        accountTypeLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        accountTypeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountTypeLabel1.setText("Account Type");

        accountTypeTextField.setEditable(false);

        accountNumberTextField1.setEditable(false);

        transactionButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        transactionButton.setText("Transaction History");
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });

        accountNumberLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        accountNumberLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumberLabel1.setText("Account Number");

        accountBalanceTextField1.setEditable(false);
        accountBalanceTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountDetailsPanelLayout = new javax.swing.GroupLayout(accountDetailsPanel);
        accountDetailsPanel.setLayout(accountDetailsPanelLayout);
        accountDetailsPanelLayout.setHorizontalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addComponent(accountNumberLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                        .addComponent(accountNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountTypeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountBalanceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(transactionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountDetailsPanelLayout.setVerticalGroup(
            accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountBalanceLabel1)
                    .addComponent(accountTypeLabel1)
                    .addComponent(accountNumberLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transactionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        depositWithdrawalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deposit / Withdrawal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13))); // NOI18N

        depositButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawalButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        withdrawalButton.setText("Withdrawal");
        withdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalButtonActionPerformed(evt);
            }
        });

        amountLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        amountLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountLabel2.setText("Amount");

        javax.swing.GroupLayout depositWithdrawalPanelLayout = new javax.swing.GroupLayout(depositWithdrawalPanel);
        depositWithdrawalPanel.setLayout(depositWithdrawalPanelLayout);
        depositWithdrawalPanelLayout.setHorizontalGroup(
            depositWithdrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositWithdrawalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositWithdrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(amountTextField1)
                    .addComponent(amountLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(depositWithdrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depositWithdrawalPanelLayout.setVerticalGroup(
            depositWithdrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositWithdrawalPanelLayout.createSequentialGroup()
                .addGroup(depositWithdrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(depositWithdrawalPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depositButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawalButton))
                    .addGroup(depositWithdrawalPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(amountLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );

        transferPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transfer / Pay Mortgage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 13))); // NOI18N

        payMortgageButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        payMortgageButton.setText("Pay Mortgage");
        payMortgageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payMortgageButtonActionPerformed(evt);
            }
        });

        transferButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        amountTextField2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        accountTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        amountLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amountLabel.setText("Amount");

        accountNumberLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        accountNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumberLabel.setText("Account Number");

        javax.swing.GroupLayout transferPanelLayout = new javax.swing.GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountTextField)
                    .addComponent(accountNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(transferButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payMortgageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(transferButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payMortgageButton)
                .addGap(7, 7, 7))
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel)
                    .addComponent(accountNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backToCustomerButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        backToCustomerButton.setText("Go Back");
        backToCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCustomerButtonActionPerformed(evt);
            }
        });

        deleteAccountButton.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        deleteAccountButton.setText("Delete This Account");
        deleteAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAccountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(depositWithdrawalPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accountDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(backToCustomerButton)
                .addContainerGap(149, Short.MAX_VALUE))
            .addComponent(bannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bannerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositWithdrawalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAccountButton)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToCustomerButton)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        Transactions t = new Transactions();
            String account = accountNumberTextField1.getText();
            String transactions = bankingDAO.getTransactionHistory(account);
            Scanner stdin = new Scanner(transactions);
           
            int i = 0;
            while(stdin.hasNext()) {
                for (int j=0; j<6; j++) {
                    t.setTransactionInformation(stdin.nextLine(), i, j);
                } //end for
                i++;
                
            } //end while
            
            t.setVisible(true);
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void backToCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCustomerButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backToCustomerButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        String accountNumber = accountNumberTextField1.getText();
        String depositAmount = amountTextField1.getText();
        
        //Process deposit
        String newBalance = bankingDAO.depositMoney(accountNumber, depositAmount);
        
        if (!newBalance.contains("Error"))
        {
            JOptionPane.showMessageDialog((Component) null, 
                    "Your new balance is: " + newBalance,
    	       "Account Balance", JOptionPane.OK_OPTION);
            accountBalanceTextField1.setText(newBalance);
        }
        else {
            JOptionPane.showMessageDialog((Component) null, 
                    "An error has occured",
    	       "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalButtonActionPerformed
        String accountNumber = accountNumberTextField1.getText();
        String withdrawalAmount = amountTextField1.getText();
        
            //Process withdrawal
            String newBalance = bankingDAO.withdrawMoney(accountNumber, withdrawalAmount);
        
        if (!newBalance.contains("Error"))
        {
            JOptionPane.showMessageDialog((Component) null, 
                    "Your new balane is: " + newBalance,
    	       "Account Balance", JOptionPane.OK_OPTION);
            accountBalanceTextField1.setText(newBalance);
        }
        else {
            JOptionPane.showMessageDialog((Component) null, 
                    "An error has occured",
    	       "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_withdrawalButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        String accountNumber = accountNumberTextField1.getText();
        String toAccountNumber = accountTextField.getText();
        String transferAmount = amountTextField2.getText();
        
        String amounts = bankingDAO.transferMoney(accountNumber, transferAmount, toAccountNumber);
        Scanner stdin = new Scanner(amounts);
        String accountNewBalance = stdin.next();
        
        //Process transfer
        if (!accountNewBalance.contains("Error"))
        {
            JOptionPane.showMessageDialog((Component) null, 
                    "Your new balance is: " + accountNewBalance,
    	       "Account Balance", JOptionPane.OK_OPTION);
            accountBalanceTextField1.setText(accountNewBalance);
        }
        else {
            JOptionPane.showMessageDialog((Component) null, 
                    "An error has occured",
    	       "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_transferButtonActionPerformed

    private void payMortgageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payMortgageButtonActionPerformed
        String acctNumberfrom = accountNumberTextField1.getText();
        String mortgageAccount = accountTextField.getText();
        String amount = amountTextField2.getText();
        
        //Transmit account information
        String newBalance = bankingDAO.payMortgage(acctNumberfrom, amount, mortgageAccount);
        
        Scanner stdin = new Scanner(newBalance);
        String newAccountBalance = stdin.next();
        String newMortgageBalance = stdin.next();
        
        if (!newBalance.contains("Error"))
        {
            JOptionPane.showMessageDialog((Component) null, 
                    "Your new mortage balance is: " + newMortgageBalance
                    + "\n Your new account balance is: " + newAccountBalance,
    	       "Mortage", JOptionPane.OK_OPTION);
            accountBalanceTextField1.setText(newAccountBalance);
        }
        else {
            JOptionPane.showMessageDialog((Component) null, 
                    "An error has occured" + newBalance,
    	       "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_payMortgageButtonActionPerformed

    private void deleteAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAccountButtonActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this account", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            //Delete account
            bankingDAO.deleteAccount(accountNumberTextField1.getText());
            this.dispose();
        }
    }//GEN-LAST:event_deleteAccountButtonActionPerformed

    private void accountBalanceTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceTextField1ActionPerformed

    
    public void setTopAccountInfo(String number, String type, String balance) {
        accountBalanceTextField1.setText(balance);
        accountTypeTextField.setText(type);
        accountNumberTextField1.setText(number);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalanceLabel1;
    private javax.swing.JTextField accountBalanceTextField1;
    private javax.swing.JPanel accountDetailsPanel;
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JLabel accountNumberLabel1;
    private javax.swing.JTextField accountNumberTextField1;
    private javax.swing.JTextField accountTextField;
    private javax.swing.JLabel accountTypeLabel1;
    private javax.swing.JTextField accountTypeTextField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel2;
    private javax.swing.JTextField amountTextField1;
    private javax.swing.JTextField amountTextField2;
    private javax.swing.JButton backToCustomerButton;
    private javax.swing.JLabel bannerLabel;
    private javax.swing.JButton deleteAccountButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel depositWithdrawalPanel;
    private javax.swing.JButton payMortgageButton;
    private javax.swing.JButton transactionButton;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JButton withdrawalButton;
    // End of variables declaration//GEN-END:variables
}
